[settings]

[entries]
"/home/thatmagicalcat/dotfiles/fish" = "/home/thatmagicalcat/.config/fish"
"/home/thatmagicalcat/dotfiles/helix" = "/home/thatmagicalcat/.config/helix"
"/home/thatmagicalcat/dotfiles/dwm-statusbar" = "/home/thatmagicalcat/.config/dwm-statusbar"
"/home/thatmagicalcat/dotfiles/ghostty" = "/home/thatmagicalcat/.config/ghostty"
"/home/thatmagicalcat/dotfiles/nix" = "/home/thatmagicalcat/nix"
"/home/thatmagicalcat/dotfiles/opencode" = "/home/thatmagicalcat/.config/opencode"
"/home/thatmagicalcat/dotfiles/waybar" = "/home/thatmagicalcat/.config/waybar"
"/home/thatmagicalcat/dotfiles/alacritty" = "/home/thatmagicalcat/.config/alacritty"
"/home/thatmagicalcat/dotfiles/kitty" = "/home/thatmagicalcat/.config/kitty"
"/home/thatmagicalcat/dotfiles/fastfetch" = "/home/thatmagicalcat/.config/fastfetch"
"/home/thatmagicalcat/dotfiles/starship.toml" = "/home/thatmagicalcat/.config/starship.toml"
"/home/thatmagicalcat/dotfiles/nvim" = "/home/thatmagicalcat/.config/nvim"
"/home/thatmagicalcat/dotfiles/picom.conf" = "/home/thatmagicalcat/.config/picom.conf"
"/home/thatmagicalcat/dotfiles/niri" = "/home/thatmagicalcat/.config/niri"
"/home/thatmagicalcat/dotfiles/river" = "/home/thatmagicalcat/.config/river"
"/home/thatmagicalcat/dotfiles/dwm" = "/home/thatmagicalcat/.config/dwm"
"/home/thatmagicalcat/dotfiles/rofi" = "/home/thatmagicalcat/.config/rofi"
"/home/thatmagicalcat/dotfiles/Scripts" = "/home/thatmagicalcat/Scripts"
